### ISSUE TITLE
OAM compatibility 

### ISSUE THREAD

**Issue by DustinFlynn297** [department-of-veterans-affairs/lighthouse-saml-proxy#417]
Hey, this isn't necessarily an issue. But more of a question for the author/contributors. I see that this was designed for the purpose of using Okta for the dept of veterans affairs.

I'm currently working for another gov project and we are leveraging OAM. How difficult would it be to adapt this to use our OAM IDP and just use the SP proxy portion of this project? If you were to gauge it on  the Fibonacci scale, how many points would you think it would take to make this work assuming little to no experience with SAML?

Not sure who the author or best person to answer this inquiry would be. Tagging a few people for reach

@edpaget @avallee @jpf @dvogel

**Comment by crolarlibertyva** [comment]
Hi.

Before I can answer, need to make sure you have a fuller picture of this apps purpose. This proxy serves as the 1st stage bridge between Okta and other IDPs, eg Login.gov and ID.me. In this case, Okta is the OIDC token provider which gives authorization to the target API's This 2nd proxy at https://github.com/department-of-veterans-affairs/lighthouse-oauth-proxy, used for the authorization stage, can also interoperate with other OIDC Oauth2 providers, eg. OKta, and SSOi in our case.  I'm not sure which standard OAM implements, but if it's Oauth2 the 2nd proxy might be a better fit? As far as this proxy goes, it specially, calls other va services as part of validating the authentication. That would be where the extra effort would come in versus posting assertions to Okta.  An in-the-dark guess on the Fibonacci would be a 5 or 8 w/o more knowledge on OAM, eg. is just an IDP or authorization services as well.

**Comment by DustinFlynn297** [comment]
I think this does a little bit more than what we are currently looking for right now. Thank you so much for the detailed explanation.
